### ISSUE TITLE
error message on webhook 

### ISSUE THREAD

**Issue by vkjuju** [thekosmix/Java-FbChatBot#2]
WE hit the following error when we pasted it on facebook messenger webhook:

The URL couldn't be validated. Response does not match challenge, expected value="663821411", received=""

url:  https://41ab4ddb.ngrok.io/bot/webhook?hub.verify_token=nhitoken&hub.challenge=123456

any advice would be appreciated

**Comment by vkjuju** [comment]
any advice ? Thanks

**Comment by vkjuju** [comment]
it worked by this url: https://41ab4ddb.ngrok.io/bot/webhook?hub.verify_token=whatever_string_you_or_your_friends_wish&hub.challenge=joeyang

**Comment by vkjuju** [comment]
but we still get the following error from 9090 server console(eclipse):
webhook servlet created!!
java.io.IOException: Server returned HTTP response code: 400 for URL: https://graph.facebook.com/v2.6/1815549365137695?access_token=YOUR_FB_PAGE_TOKEN
[ERROR] /bot/webhook
java.lang.NullPointerException
	at in.strollup.fb.utils.FbChatHelper.getReplies(FbChatHelper.java:117)
	at in.strollup.fb.servlet.WebHookServlet.sendTextMessage(WebHookServlet.java:147)
	at in.strollup.fb.servlet.WebHookServlet.processRequest(WebHookServlet.java:123)
	at in.strollup.fb.servlet.WebHookServlet.doPost(WebHookServlet.java:55)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:362)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:726)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:206)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:324)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:505)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:843)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:648)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:380)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:395)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:488)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at java.net.URL.openStream(URL.java:1045)
	at in.strollup.fb.utils.FbChatHelper.getObjectFromUrl(FbChatHelper.java:262)
	at in.strollup.fb.utils.FbChatHelper.getReplies(FbChatHelper.java:115)
	at in.strollup.fb.servlet.WebHookServlet.sendTextMessage(WebHookServlet.java:147)
	at in.strollup.fb.servlet.WebHookServlet.processRequest(WebHookServlet.java:123)
	at in.strollup.fb.servlet.WebHookServlet.doPost(WebHookServlet.java:55)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:362)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:726)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:206)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:324)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:505)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:843)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:648)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:380)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:395)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:488)
[ERROR] /bot/webhook

**Comment by thekosmix** [comment]
I can see this code segment `profile.getFirstName()` on the said lines. 
It seems fb is not giving the user's profile you're trying to get. You can try to resolve it by putting debug point on the said lines.

**Comment by vkjuju** [comment]
do we have to edit anything in WebHookServlet.java ? Thanks

**Comment by vkjuju** [comment]
the error came from this url: java.io.IOException: Server returned HTTP response code: 400 for URL: https://graph.facebook.com/v2.6/1503979472975191?access_token=YOUR_FB_PAGE_TOKEN

any more advice ?

**Comment by vkjuju** [comment]
do we have to modify this code?  public static final String PAGE_TOKEN = "YOUR_FB_PAGE_TOKEN";

**Comment by vkjuju** [comment]
@thekosmix , can you still run it successfully on facebook messenger ?

**Comment by thekosmix** [comment]
do we have to modify this code? public static final String PAGE_TOKEN = "YOUR_FB_PAGE_TOKEN";
Yes, you'll have to modify it. You'll have to put the fb token you got from developer's console!! 

can you still run it successfully on facebook messenger ?
Yes, I'm still able to
